config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :links, except: :show
  get '/:slug', to: 'links#show', as: :short
  root 'links#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  validates :url, presence: true
  validates :slug, uniqueness: true

  scope :frequent_links, -> { order(visited: :desc).limit(100) }

  def short
    Rails.application.routes.url_helpers.short_url(slug: self.slug)
  end

  def self.generate_link(url)
    link = Link.new(url: url)
    return link unless link.valid?

    link.slug = SecureRandom.uuid[0..5]
    if link.save
      # run a background job here to get the title
      TitleFetcherJob.perform_later(link.id)
      return link
    end
    Link.generate_link(url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    if Rails.env.production?
      Rails.application.routes.default_url_options = { host: "www.production-domain.com", protocol: 'https' }
    elsif Rails.env.development?
      Rails.application.routes.default_url_options = { host: 'localhost:3000', protocol: 'http' }
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def show
    @link = Link.find_by_slug(params[:slug])
    if @link.nil?
      render file: 'public/404.html', status: :not_found, layout: false
    else
      @link.update_attribute(:visited, @link.visited + 1)
      redirect_to @link.url
    end
  end

  def new
    @link = Link.new
  end

  def index
    @frequent_links = Link.frequent_links
  end

  def create
    @link = Link.generate_link(link_params[:url])
    if @link.save
      @frequent_links = Link.frequent_links
      flash[:notice] = 'You have successfully shortened URL.'
      render :index
    else
      render 'new'
    end
  end

  private

  def link_params
    params.require(:link).permit(:url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button aria-hidden="true" class="close" data-dismiss="alert" type="button">&times;</button>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortner</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/links/index.html.erb
<h3>Welcome to URL Shortner</h3>

<% if @link.present? %>
  <p>Shortend Link: <%= link_to @link.short, @link.short %></p>
<% end %>
<%= link_to 'Shorten URL', new_link_path %>
<hr>
<h4 class="text-center">Frequently accessed URLs</h4>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Long URL</th>
      <th>Short URL</th>
      <th>Visits</th>
    </tr>
    <t>
  </thead>
  <tbody>
    <% @frequent_links.each do |fl| %>
      <tr>
        <td><%= fl.title %></td>
        <td><%= fl.url %></td>
        <td><%= fl.short %></td>
        <td><%= fl.visited %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/links/new.html.erb
<h3>Shorten URL:</h3>
<%= form_with model: @link, local: true, class: 'mb-2' do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@link.errors.count, "error") %> prohibited
        this link from being shortened:
      </h2>
      <ul>
        <% @link.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :url, class: 'form-control mb-2' %>
  <%= f.submit 'Create Short URL',class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back', root_path, class: 'btn btn-secondary' %>